/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDC;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRegisterationRequest;
import Business.WorkQueue.VaccinationVendor;
import Business.WorkQueue.VaccineManufacturerRequest;
import Business.WorkQueue.VaccineProductionRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author naren
 */
public class CDCAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CDCAdminJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private VaccinationVendor vaccinationVendor;
    private VaccineProductionRequest VaccineProductionRequest;
    
    public CDCAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateVendorListTable();
        populateManufacturerListTable();
    }
    
    public void populateManufacturerListTable(){
       
                
        DefaultTableModel dtm = (DefaultTableModel) vaccineManu.getModel();
        dtm.setRowCount(0);
        System.out.println(system.getNetworkList().size());
        for(Network n : system.getNetworkList()){
               
            for( Enterprise e : n.getEnterpriseDirectory().getEnterpriseDirectoryList()){
                for( WorkRequest workRequest : e.getWorkQueue().getWorkRequestList() ){
                    if(workRequest instanceof VaccineProductionRequest){
                        System.out.println("w "+ workRequest);
                        Object row[] = new Object[5];
                        row[0] = ((VaccineProductionRequest) workRequest);
                        row[1] = ((VaccineProductionRequest) workRequest).getEfficiency();
                        row[2] = ((VaccineProductionRequest) workRequest).getNumberofdoses();
                        row[3] = ((VaccineProductionRequest) workRequest).getStatus();
                        row[4] = ((VaccineProductionRequest) workRequest).getRequestDate();
                       
                        dtm.addRow(row);
                    }
                }
            }
               
        }
    }
   
    public void populateVendorListTable(){
       
                
        DefaultTableModel dtm = (DefaultTableModel) VendorListtbl.getModel();
        dtm.setRowCount(0);
        System.out.println(system.getNetworkList().size());
        for(Network n : system.getNetworkList()){
               
            for( Enterprise e : n.getEnterpriseDirectory().getEnterpriseDirectoryList()){
                for( WorkRequest workRequest : e.getWorkQueue().getWorkRequestList() ){
                    if(workRequest instanceof VaccinationVendor){
                        System.out.println("w "+ workRequest);
                        Object row[] = new Object[6];
                        row[0] = ((VaccinationVendor) workRequest);
                        row[1] = ((VaccinationVendor) workRequest).getEmail();
                        row[2] = ((VaccinationVendor) workRequest).getAddress();
                        row[3] = ((VaccinationVendor) workRequest).getCity();
                        row[4] = ((VaccinationVendor) workRequest).getState();
                        row[5] = ((VaccinationVendor) workRequest).getStatus();
                        dtm.addRow(row);
                    }
                }
            }
               
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        VendorListtbl = new javax.swing.JTable();
        Approvebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vaccineManu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VendorListtbl.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        VendorListtbl.setForeground(new java.awt.Color(0, 51, 153));
        VendorListtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Email ID", "Address", "City", "State", "Status"
            }
        ));
        VendorListtbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VendorListtbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jScrollPane1.setViewportView(VendorListtbl);
        if (VendorListtbl.getColumnModel().getColumnCount() > 0) {
            VendorListtbl.getColumnModel().getColumn(0).setResizable(false);
            VendorListtbl.getColumnModel().getColumn(0).setHeaderValue("Name");
            VendorListtbl.getColumnModel().getColumn(1).setResizable(false);
            VendorListtbl.getColumnModel().getColumn(1).setHeaderValue("Email ID");
            VendorListtbl.getColumnModel().getColumn(2).setResizable(false);
            VendorListtbl.getColumnModel().getColumn(2).setHeaderValue("Address");
            VendorListtbl.getColumnModel().getColumn(3).setResizable(false);
            VendorListtbl.getColumnModel().getColumn(3).setHeaderValue("City");
            VendorListtbl.getColumnModel().getColumn(4).setResizable(false);
            VendorListtbl.getColumnModel().getColumn(4).setHeaderValue("State");
            VendorListtbl.getColumnModel().getColumn(5).setResizable(false);
            VendorListtbl.getColumnModel().getColumn(5).setHeaderValue("Status");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 720, 130));

        Approvebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Approvebtn.setForeground(new java.awt.Color(0, 51, 153));
        Approvebtn.setText("Approve");
        Approvebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprovebtnActionPerformed(evt);
            }
        });
        add(Approvebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Hnet.com-image (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 620, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CDC DASHBOARD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 290, -1));

        vaccineManu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Vaccine Efficiiency", "No. of Doses", "Status", "Requested Date"
            }
        ));
        jScrollPane2.setViewportView(vaccineManu);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 720, 120));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 153));
        jButton3.setText("Reject");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ApprovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprovebtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = VendorListtbl.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        vaccinationVendor = (VaccinationVendor)VendorListtbl.getValueAt(selectedRow,0);
        vaccinationVendor.setStatus("Approved");
        populateVendorListTable();
         
         HashMap<String, Integer> map = new HashMap<>();
         map.put("Pfizer", 10);
         map.put("Moderna", 10);
         map.put("Johnson & Johnson", 10);
         vaccinationVendor.setStockOne(map);
         System.out.println("Map 1 values : "+map);
         
//         HashMap<String, Integer> map1 = new HashMap<>();
//         map1.put("Pfizer", 10);
//         map1.put("Moderna", 10);
//         map1.put("Johnson & Johnson", 0);
//         vaccinationVendor.setStockTwo(map1);
//         System.out.println("Map 2 values : "+map1);
         
 
    }//GEN-LAST:event_ApprovebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int selectedRow = VendorListtbl.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        vaccinationVendor = (VaccinationVendor)VendorListtbl.getValueAt(selectedRow,0);
        vaccinationVendor.setStatus("Rejected");
        populateVendorListTable(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = vaccineManu.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VaccineProductionRequest = (VaccineProductionRequest)vaccineManu.getValueAt(selectedRow,0);
        VaccineProductionRequest.setStatus("Approved");
        
        populateManufacturerListTable(); 
        
        VaccineManufacturerRequest vaccineManufacturerRequest2 = new VaccineManufacturerRequest
        (VaccineProductionRequest.getName(), VaccineProductionRequest.getEfficiency(), 
                VaccineProductionRequest.getManufacturername(), VaccineProductionRequest.getNumberofdoses(), "SASAS", new Date());
        vaccineManufacturerRequest2.setStatus("Approved");
        Network network = system.searchNetworkName(VaccineProductionRequest.getState());
        if(network ==null){
            network = new Network();
            network.setNetworkName(VaccineProductionRequest.getState());
            system.setNetworkList(network);
        }
        if(network.getEnterpriseDirectory() == null){
            EnterpriseDirectory ed = new EnterpriseDirectory();
            ed.createAndAddEnterprise("PublicHealthDepartment", 
                    Enterprise.EnterpriseType.PublicHealthDepartment);
            network.setEnterpriseDirectory(ed);
            
        }
        for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseDirectoryList()){
                
                if(e.getEnterpriseType() == Enterprise.EnterpriseType.PublicHealthDepartment){
                    if(e.getWorkQueue()==null){
                        e.setWorkQueue(new WorkQueue());
                    }
                    e.getWorkQueue().getWorkRequestList().add(vaccineManufacturerRequest2);
                    System.out.println("Added ");
                    return;               

                }
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = vaccineManu.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VaccineProductionRequest = (VaccineProductionRequest)vaccineManu.getValueAt(selectedRow,0);
        VaccineProductionRequest.setStatus("Rejected");
        populateManufacturerListTable(); 
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approvebtn;
    private javax.swing.JTable VendorListtbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable vaccineManu;
    // End of variables declaration//GEN-END:variables
}
