/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Patient.PatientRegisterJPanel;
import userinterface.SystemAdminWorkArea.NewManufacturerJPanel;
import userinterface.VaccineManufacturer.VaccineManufacturerJPanel;
import userinterface.Vendor.VendorSignUpJPanel;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    JPanel userProcessContainer;
    UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setSize(1680, 1050);
        jPanel1 = new javax.swing.JPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        vaccineManufacturer = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Hnet.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginJButton.setBackground(new java.awt.Color(255, 255, 255));
        loginJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginJButton.setForeground(new java.awt.Color(0, 51, 153));
        loginJButton.setText("Login");
        loginJButton.setOpaque(false);
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, -1));
        jPanel1.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 157, -1));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 157, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(loginJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 240, -1, -1));

        logoutJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutJButton.setForeground(new java.awt.Color(0, 51, 153));
        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.setOpaque(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 131, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Register User");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 157, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Register Vendor");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 157, -1));

        vaccineManufacturer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vaccineManufacturer.setForeground(new java.awt.Color(0, 51, 153));
        vaccineManufacturer.setText("Vaccine Manufacturer");
        vaccineManufacturer.setOpaque(false);
        vaccineManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineManufacturerActionPerformed(evt);
            }
        });
        jPanel1.add(vaccineManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 510, 150, 50));

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Hnet.png"))); // NOI18N
        jPanel2.add(jLabel4, "card2");

        container.add(jPanel2, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
          // Get user name
        String userName = userNameJTextField.getText().trim();
        char[] passa = passwordField.getPassword();
        String password = String.valueOf(passa);
        
        System.out.println("USS "+ userName);
                System.out.println("Pass "+ password);

        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
        
//        System.out.println("Syss "+ system.getSupportedRole().);
//        EcoSystem inEcoSystem =null;
//        System.out.println("UAA "+ userAccount);
//        Organization inOrganization=null;
        
//        
//        if(userAccount==null){
//            //Step 2: Go inside each network and check each enterprise
//           // for(Network network:system.getNetworkList()){
//                //Step 2.a: check against each enterprise
//                for(Enterprise enterprise:system.getEnterpriseDirectory().getEnterpriseList())
//                {
//                    //userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
//                    if(userAccount==null)
//                    {
//                       //Step 3:check against each organization for each enterprise
//                       for(Organization organization:enterprise.getRestaurantDirectory().getOrganizationList())
//                       {
//                           userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
//                           if(userAccount!=null)
//                           {
//                               inEnterprise=enterprise;
//                               inOrganization=organization;
//                               break;
//                           }
//                       }
//                    }
//                    
//                    else{
//                       inEnterprise=enterprise;
//                       break;
//                    }
//                    if(inOrganization!=null){
//                        break;
//                    }  
//                }
//        }
        
       // step-3 --to check for customer users
       
//        if(userAccount==null){
//           for(Organization organization: system.getCustomerDirectory().getOrganizationList())
//                       {
//                           userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
//                           if(userAccount!=null)
//                           {
//                               inOrganization=organization;
//                               break;
//                           }
//                       }
//        }
//         //step-4--to check for deliver users
//               if(userAccount==null){
//           for(Organization organization:system.getDeliveryManDirectory().getOrganizationList())
//                       {
//                           userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
//                           if(userAccount!=null)
//                           {
//                               inOrganization=organization;
//                               break;
//                           }
//                       }
//        }
        
        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, system));
            //container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEcoSystem, system));
            layout.next(container);
                
               
            
        }
        
        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(true);
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
       
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
//        JPanel blankJP = new JPanel();
        container.add("blank", jPanel2);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)container.getLayout();
        container.add(new PatientRegisterJPanel(container, system));
        layout.next(container);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Vendor Register");
        CardLayout layout=(CardLayout)container.getLayout();
        container.add(new VendorSignUpJPanel(container, system));
        layout.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vaccineManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineManufacturerActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)container.getLayout();
        container.add(new NewManufacturerJPanel(container, system, userAccount));
        layout.next(container);
        
    }//GEN-LAST:event_vaccineManufacturerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JButton vaccineManufacturer;
    // End of variables declaration//GEN-END:variables
}
