/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccinationSitesAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.WorkQueue.PatientRegisterationRequest;
import Business.WorkQueue.VaccinationVendor;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naren
 */
public class VaccinationSitesAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccinationSitesAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    VaccinationVendor vaccinationVendor;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
//    public VaccinationSitesAdminWorkAreaJPanel() {
//        initComponents();
//    }
    
    public VaccinationSitesAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        populateVendorListTable();
        //populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VaccinationSitetbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        NewSitebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VACCINATION SITE ADMINISTRATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 534, 55));

        VaccinationSitetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "City", "State", "Email ID"
            }
        ));
        jScrollPane1.setViewportView(VaccinationSitetbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 609, 121));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("List of Vaccination Sites");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        NewSitebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewSitebtn.setForeground(new java.awt.Color(0, 51, 153));
        NewSitebtn.setText("Add New Site");
        NewSitebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSitebtnActionPerformed(evt);
            }
        });
        add(NewSitebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images (1).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 440, 140));
    }// </editor-fold>//GEN-END:initComponents

    
    private void NewSitebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSitebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewSitebtnActionPerformed

    public void populateVendorListTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) VaccinationSitetbl.getModel();
        dtm.setRowCount(0);
        System.out.println(ecosystem.getNetworkList().size());
        for(Network n : ecosystem.getNetworkList()){
               
            for( Enterprise e : n.getEnterpriseDirectory().getEnterpriseDirectoryList()){
                for( WorkRequest workRequest : e.getWorkQueue().getWorkRequestList() ){
                    if(workRequest instanceof VaccinationVendor){
                        System.out.println("w "+ workRequest);
                        if(((VaccinationVendor) workRequest).getStatus().equals("Approved")){
                          Object row[] = new Object[5];
                        row[0] = ((VaccinationVendor) workRequest).getName();
                        row[1] = ((VaccinationVendor) workRequest).getEmail();
                        row[2] = ((VaccinationVendor) workRequest).getAddress();
                        row[3] = ((VaccinationVendor) workRequest).getCity();
                        row[4] = ((VaccinationVendor) workRequest).getState();
                        dtm.addRow(row);
                        }
                    }
                }
            }
               
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewSitebtn;
    private javax.swing.JTable VaccinationSitetbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
