/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;

import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.PatientRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author psrib
 */
public class PatientRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientRegisterJPanel
     */
    EcoSystem system;
    private JPanel userProcessContainer;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public PatientRegisterJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=ecoSystem;
        //this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 70, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("State");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("PATIENT REGISTRATION");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 300, -1));

        state.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        state.setForeground(new java.awt.Color(0, 51, 153));
        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "California", "Massachusetts" }));
        add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 164, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Username");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 80, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        name.setCaretColor(new java.awt.Color(0, 51, 153));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 164, -1));

        username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        username.setCaretColor(new java.awt.Color(0, 51, 153));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 164, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/123-1235304_clip-art-cartoon-picture-of-doctor-and-patient (3).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 590, 450));
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//<<<<<<< Updated upstream
  //      Network network;
   //     String uname = username.getText();
   //     String password = pass.getText();
  //      String emailId = email.getText();
   //     String stateName = String.valueOf(state.getSelectedItem());
//        if(system.getNetworkDirectory()==null){
//            network = new Network();
//            network.setNetworkName(stateName);
//        }else{
//            network = system.getNetworkDirectory().searchNetworkName(stateName);
//        }
//        Enterprise enterprise ;
//        if(network.getEnterpriseDirectory()==null){
//            enterprise = new Enterprise();
//            enterprise.setEnterpriseName("PHD");
//            EnterpriseDirectory ed = new EnterpriseDirectory();
//            ArrayList<Enterprise> enterprises = new ArrayList<>();
//            enterprises.add(enterprise);
//            ed.setEnterpriseList(enterprises);
//            if(enterprise.getOrganization() == null){
//                Organization org = new Organization("Patient");
//                
//                
//            }
//            
//            enterprise.getOrganization().getUserAccountDirectory().createUserAccount(uname, password, new CustomerRole());
//
//        }else{               
//            enterprise = network.getEnterpriseDirectory().searchEnterprise("PHD");
//            enterprise.getOrganization().getUserAccountDirectory().createUserAccount(uname, password, new CustomerRole());
//            
//        }
            
        dB4OUtil.storeSystem(system);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

//        Employee emp = new Employee();
//        emp.setName(name.getText());
//        system.getUserAccountDirectory().createUserAccount(username.getText(), pass.getText(), emp, new PatientRole());
//        dB4OUtil.storeSystem(system);    
                                                 

    private boolean strongUsername() {
        Pattern pat = Pattern.compile("^(?=.?[A-Z])(?=.?[a-z])(?=.?[0-9])(?=.?[#?!@$%^&*-]).{6,}$");
        Matcher m = pat.matcher(username.getText());
        boolean boo = m.matches();
        return boo;
    }

//    private boolean strongPassword() {
//        Pattern pat1;
//        pat1 = Pattern.compile("^(?=.?[A-Z])(?=.?[a-z])(?=.?[0-9])(?=.?[#?!@$%^&*-]).{6,}$");
//        Matcher m1 = pat1.matcher(pass.getText());
//        boolean bat1 = m1.matches();
//        return bat1;
//    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        char[] passa = pass.getPassword();
        String password = String.valueOf(passa);
        
        Employee emp = new Employee();
        emp.setName(name.getText());
        System.out.println("Name "+ name.getText());
        system.getUserAccountDirectory().createUserAccount(username.getText(), password, emp, new PatientRole());

        if(name.getText().isEmpty() || username.getText().isEmpty() || password.isEmpty() || pass.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "All the fields are required", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
           return;

        }
        
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Successfully Registered", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
