/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ExternalDepartments;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ClinicRegistrationRequest;
import Business.WorkQueue.PatientRegisterationRequest;
import Business.WorkQueue.VaccineManufacturerRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author psrib
 */
public class ExternalDepartmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExternalDepartmentJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    
    private PatientRegisterationRequest patientRegisterationRequest;

    private ClinicRegistrationRequest c;



    public ExternalDepartmentJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
       // this.userAccount = account;
        this.system = system;
       
       //populatePatientTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uniqueID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        dateL = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("VERIFY VACCINATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 300, 36));
        add(uniqueID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 140, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Verify Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Vaccination ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 138, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Clinic Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 209, -1, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 65, 228, -1));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 228, -1));
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 228, -1));

        dateL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateL.setForeground(new java.awt.Color(0, 51, 153));
        dateL.setText("Date");
        jPanel1.add(dateL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 228, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 480, 340));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mass-vaccination-against-covid-19_132718-126.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 580, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            
        Boolean flag = false;
         for(Network n : system.getNetworkList()){
               
            for( Enterprise e : n.getEnterpriseDirectory().getEnterpriseDirectoryList()){
                for( WorkRequest workRequest : e.getWorkQueue().getWorkRequestList() ){
                    if(workRequest instanceof PatientRegisterationRequest && ((PatientRegisterationRequest) workRequest).getUniqueID()
                            .equals(uniqueID.getText())){
                        System.out.println("w "+ workRequest);
                                             
                        patientRegisterationRequest = (PatientRegisterationRequest) workRequest;
                        flag = true;
                    }
                }
            }
               
        }
         if(!flag){
            JOptionPane.showMessageDialog(null, "No records found", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);

         }
        name.setText(patientRegisterationRequest.getName());
        status.setText(patientRegisterationRequest.getStatus());
        name2.setText(patientRegisterationRequest.getClinicRegistrationRequest().getClinicName());
        date.setText(patientRegisterationRequest.getClinicRegistrationRequest().getFirstDoseDate());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField status;
    private javax.swing.JTextField uniqueID;
    // End of variables declaration//GEN-END:variables
}
